### ISSUE TITLE
Odd behavior while editing buffer

### ISSUE THREAD

**Issue by Fedreg** [emacs-lsp/lsp-java#102]
First off, thanks to all who are working on this project! Outstanding!

Started using lsp-mode to work on a small Spring project.  For most repos it has worked great. On one particular project/namespace even the tiniest edits cause lots of changes to the source code.  See picture below.  In this case all I did was change the var `US_EAST_2` to US_EAST_1` and I get that huge diff and those odd `^M` characters.   My config is exactly what is shown in the lsp-java repo.  Any thoughts?   I'll add that the closest I usually get to Java is Clojure so very possible it is something on my end.  thx!

All my packages are up to date.  Can't paste my source code because it is a work project.  
<img width="682" alt="image" src="https://user-images.githubusercontent.com/17401067/52684791-0ff05600-2f0d-11e9-9ae6-a48f73097f0e.png">

*lsp-log* shows this
<img width="510" alt="image" src="https://user-images.githubusercontent.com/17401067/52685088-10d5b780-2f0e-11e9-8b47-1ee8786fcf41.png">
Flycheck errors?

**Comment by yyoncho** [comment]
1. ^M are windows file endings which are preserved by the JDT LS formatter. You have 2 options:
a) Change emacs to do not display them via something like https://stackoverflow.com/questions/730751/hiding-m-in-emacs
b) Change the line endings in this fine using dos2unix for example.

2. The other changes are caused by organize imports which is performed on save. If you don't like it you may turn it off by setting lsp-java-save-action-organize-imports to nil and calling lsp-java-update-configuration or restarting the server.

**Comment by Fedreg** [comment]
@yyoncho Worked perfectly! Thank you!!
