### ISSUE TITLE
error in process filter: or: Symbol’s value as variable is void: method 

### ISSUE THREAD

**Issue by cayhorstmann** [emacs-lsp/lsp-java#123]
I installed lsp-java from melpa (version 20190409.1708) and opened a Java file. Messages

```
File mode specification error: (void-variable it)
error in process filter: or: Symbol’s value as variable is void: method
error in process filter: Symbol’s value as variable is void: method
```

appear, and none of the lsp commands do anything.

The last two are repeated many times.

I tried with emacs25 (Ubuntu 18.04), emacs26 (kelleyk/emacs PPA), with my .emacs, and with the .emacs from https://github.com/emacs-lsp/lsp-java. I recompiled all packages.The behavior is exactly the same in all cases.

**Comment by yyoncho** [comment]
Can you try with the following command:

```
emacs  -q -l lsp-start-plain.el 
```
where start plain is from here: https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el and you have to add lsp-java to the list of the packages(on this line https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el#L44) to download? I think that you have old version of dash library which is loaded instead of the latest one.

**Comment by cayhorstmann** [comment]
Thanks, that must have been it. For other people who are as ignorant as I am about Melpa, here is what I did to fix the issue. `M-x package-list-packages`, then look for `dash`. I had one installed and one much newer one listed as available. Hit the `U` key to mark for updating, then `X` to execute. Restart and the issue goes away.
