### ISSUE TITLE
Some more documentation on what to expect

### ISSUE THREAD

**Issue by favetelinguis** [emacs-lsp/lsp-java#23]
Im trying to get lsp-java working in a spacemacs layer but I find it hard to know what to exepct, below are the questions I have:
1. Right now I can only jump into classes that are in the same project, for example I can not jump into the String class.
2. When I look for references with M - ? it looks like im just doing a word search project wide and it does not take into account scope etc, just spelling.
2. What is the difference between adding a project to the workspace variable and not adding it. I see im getting some functionality even if im not adding it but im not sure what exactly is the difference.
3. On the eclipse.jdt.ls project site there is information that the project also has maven and gradel support, is any of that functionality provided with the lsp protocol and in this project?

**Comment by yyoncho** [comment]
Hi,

1) 2) Jumping into String class, finding references(see https://github.com/emacs-lsp/lsp-java/issues/18) is fixed in https://github.com/emacs-lsp/lsp-java/pull/22 and https://github.com/emacs-lsp/lsp-mode/pull/326 . After these pull requests are merged you will be able to navigate in String class, find references across classpath, etc. 

3. If a file is not part of the project only syntax errors will be reported e. g. missing return statement. The errors about missing classes, methods cannot be reported without file's classpath. 

4. I have tested the maven support and it works fine. 

Thanks,
Ivan

**Comment by favetelinguis** [comment]
How are the maven support actually materialised in this plugin, for example when i check [M2E](https://www.eclipse.org/m2e/) they list some things supported. So for example:
How can i launch maven builds, wizards for creating new projects or searching for dependencies etc or what is it that you have tested?

**Comment by yyoncho** [comment]
Hi,

Here it is what you will get by lsp-java + jdt:
* Dependency management for Eclipse build path based on Maven's pom.xml
* Resolving Maven dependencies from the Eclipse workspace without installing to local Maven repository
* Automatic downloading of the required dependencies from the remote Maven repositories

This point you can get from spacemacs+projectile:
* Launching Maven builds from within Eclipse

Automatic detection of changes in the pom.xml is not implemented by lsp-java but it is exposed by jdt.ls, I am currently working on it.

Thanks
Yo

**Comment by favetelinguis** [comment]
Ok thanks, will wait until the pull requests are merged then. It enables some features I like to have configurable like turning off some lsp-ui stuff.
