### ISSUE TITLE
Really slow when first open a java file

### ISSUE THREAD

**Issue by liushihao456** [emacs-lsp/lsp-java#43]
Hi! I want to say that this is a really impressive project and great work for Emac-users who want to do Java development! 

My problem is, when I installed this package, added some configuration to my init file just like that in Quick Start section in your instruction, and opened a java file (I had set the project directory right), my Emacs got really really slow for about 20 sec. Meanwhile I pretty much couldn't do anything, even moving my cursor became really slow too. After 20 sec or so, everything went right and it worked amazingly. Now the thing is, every time I restart emacs and open a java file, this process happens again, which is pretty annoying though. I don't know if it is meant to be like this, or I am misconfiguring something? :)

**Comment by yyoncho** [comment]
There are few things that could cause this behaviour:

1. Your emacs might not be slow but the JDT server that is staring in the background could take all system resources. You may check that by monitoring the external resources. There is similar issue for vscode https://github.com/redhat-developer/vscode-java/issues/582 

2. JDT might send a lot of messages on startup, which could be caused by:
a) Your project contains a lot of warnings and they are send to the client on startup.
b) JDT sends a lot of notifications related to project importing. 
c) ??
The following code will log the server/client communication
``` elisp
(setq lsp-print-io t)
```
This will enable logging to *messages* buffer and this will reveal whether the slowness is caused by JSON parsing on emacs side. 

3. JDT server is not initialized - it takes some time to reimport(refresh) maven projects and ussually during that time JDT server is not responsible which may cause slowness in emacs.

**Comment by yyoncho** [comment]
Seems like this will fix your issue on jdt.ls side - https://github.com/eclipse/eclipse.jdt.ls/pull/756
