### ISSUE TITLE
Create project explorer

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-java#48]
* allow browsing files + file operations
* allow browsing deps

**Comment by omajid** [comment]
In case you didn't know, there's several project explorer-like things already available for emacs. I would suggest developing this feature as an extension to one of those, rather than implementing yet another explorer.

Some examples:
- [speedbar](https://www.gnu.org/software/emacs/manual/html_node/speedbar/) and sr-speedbar
- [treemacs](https://github.com/Alexander-Miller/treemacs/blob/master/README.org)
- [neotree](https://github.com/jaypei/emacs-neotree)
- [project-explorer](https://github.com/sabof/project-explorer)

**Comment by yyoncho** [comment]
The project explorer will be integrated in treemacs. See https://github.com/Alexander-Miller/treemacs/issues/263 .

**Comment by omajid** [comment]
Oh, that's great!

**Comment by yyoncho** [comment]
Raw preview - 
![](https://user-images.githubusercontent.com/13259670/44946720-55f7a880-ae0a-11e8-8577-ec86d1c9d1cb.png)

**Comment by yyoncho** [comment]
![emacs myoncho_053](https://user-images.githubusercontent.com/13259670/45600761-a544f800-ba0a-11e8-9fcf-d913719423d8.png)
... and with icons.
