### ISSUE TITLE
treemacs integration does not work in terminal

### ISSUE THREAD

**Issue by Follpvosten** [emacs-lsp/lsp-java#74]
Running `(require 'lsp-java-treemacs)` without a GUI results in the following error: `(void-variable treemacs-icon-java)`

This is because the PNG icon variables are not set when running Emacs without a graphical environment, because it's impossible there; see https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-icons.el#L31

**Comment by yyoncho** [comment]
Thanks for reporting, I guess I will have to use something like the code in `treemacs--setup-tui-icons` .
(cc @alexander-miller )

**Comment by Alexander-Miller** [comment]
>  I guess I will have to use something like the code in treemacs--setup-tui-icons

Yes, you'll need something like this, too.

On a side note: that doesn't just happen because you run emacs in a terminal. The png icons will not be created only when they *cannot* be created. That should only happen when your emacs was compiled without support for png images, or similarly exceptional situations.

Either way properly handling terminal fallback icons does add another layer of complexity to the extensions api, so I'll be putting this on my todo list.

**Comment by yyoncho** [comment]
Here it is how it looks like after the fix:

![tilda_057](https://user-images.githubusercontent.com/13259670/47936983-1459ab80-dee8-11e8-9ef7-182ef34a9423.png)
