### ISSUE TITLE
Build output should be written in its own buffer

### ISSUE THREAD

**Issue by iocanel** [emacs-lsp/lsp-java#99]
I would like to be able to see the build output each time I am building the project. Right now the only output I see is in the Messages buffer. It would be better if it used its own buffer. That would give a better sense of the progress, inform about errors etc.

**Comment by yyoncho** [comment]
This one is on my list.

1. Build progress will be visible in the modeline (similar to what vscode has). The messages where printed in the message area but this was very inconvenient since it was overriding the eldoc info so I decided to hide them.

2. The messages will be available in \*lsp-log\*. 

What do you think?

**Comment by iocanel** [comment]
Sounds perfect.

**Comment by yyoncho** [comment]
Implemented the following status report:

![emacs myoncho_102](https://user-images.githubusercontent.com/13259670/53289935-d8539a80-37a5-11e9-97d3-6f0818f2e008.png)
